services:

  db:
    image: 'postgres:14-alpine'
    container_name: triana
    restart: always
    environment:
      - POSTGRES_DB=triana
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5555:5432"